version = 3
final_space = true

[secondary_prompt]
template = '❯❯ '
foreground = '238'
background = 'transparent'

[transient_prompt]
template = '❯ '
background = 'transparent'
foreground_templates = [
  '{{if gt .Code 0}}red{{end}}',
  '{{if eq .Code 0}}238{{end}}',
]


[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'path'
foreground = 'white'
background = 'darkGray'
template = ' 󰉋 {{.Path}} '

[blocks.segments.properties]
style = 'full'


[[blocks.segments]]
template = '.'
background = 'black'
foreground = 'black'
type = 'text'
style = 'plain'

[[blocks.segments]]
template = '  {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
background = 'yellow'
foreground = 'white'
type = 'git'
style = 'plain'

[blocks.segments.properties]
branch_icon = ''
cache_duration = 'none'
commit_icon = '@'
fetch_status = true

[[blocks]]
type = 'rprompt'
overflow = 'hidden'


# [[blocks.segments]]
# template = '{{ .FormattedMs }}'
# foreground = 'yellow'
# background = 'transparent'
# type = 'executiontime'
# style = 'plain'
#
# [blocks.segments.properties]
# cache_duration = 'none'
# threshold = 5000

[[blocks.segments]]
type = 'python'
style = 'powerline'
template = ' {{.Venv}}'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '❯'
background = 'transparent'
foreground = '238'
type = 'text'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'

[[tooltips]]
type = "az"
tips = ["az"]
style = "plain"
foreground = "#b4f9f8"
template = " {{ .Name }}"
