export COPILOT_ALLOW_ALL=1
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ENV_HINTS=1
export MANPAGER="nvim +Man!"
export EDITOR=nvim
export PATH=$PATH:~/.local/bin
export PATH="~/.dotnet/tools:$PATH"
export ENABLE_EXPERIMENTAL_MCP_CLI=true

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

export GOPATH="$XDG_DATA_HOME/go"

# Create directory if it doesn't exist
[[ -d "$XDG_CACHE_HOME/zsh" ]] || mkdir -p "$XDG_CACHE_HOME/zsh"
