export PAGER="most"
export MANPAGER="nvim +Man!"
export EDITOR='nvim'
export PATH=$PATH:~/.local/bin
export PATH="~/.dotnet/tools:$PATH"
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

export XDG_CACHE_HOME="$HOME/.cache"

# Create directory if it doesn't exist
[[ -d "$XDG_CACHE_HOME/zsh" ]] || mkdir -p "$XDG_CACHE_HOME/zsh}"
