# Early exit for VS Code with minimal config
# if [[ "$TERM_PROGRAM" == "vscode" ]]; then
#     . "$(code-insiders --locate-shell-integration-path zsh)"
#
#     export TERM=xterm-256color
#     export PAGER=cat
#     # Disable fancy prompts for VSCode
#     PS1="%n@%m %1~ %# "
#
#     # Minimal VS Code configuration
#     HISTSIZE=10000
#     HISTFILE=~/.zsh_history
#     SAVEHIST=$HISTSIZE
#     setopt appendhistory sharehistory hist_ignore_dups
#
#     # autoload -Uz compinit && compinit
#     #
#     # PROMPT='%F{blue}%~%f %# '
#     #
#     # bindkey -v
#
#     return
# fi

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

ZVM_INIT_MODE=sourcing
ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLINKING_BEAM
ZVM_NORMAL_MODE_CURSOR=$ZVM_CURSOR_BLINKING_BLOCK
ZVM_OPPEND_MODE_CURSOR=$ZVM_CURSOR_BLINKING_UNDERLINE

source "${ZINIT_HOME}/zinit.zsh"
zinit light jeffreytse/zsh-vi-mode
zinit light Aloxaf/fzf-tab
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light zdharma-continuum/fast-syntax-highlighting

export fpath=($ZDOTDIR/func $fpath)
if command -v brew >/dev/null 2>&1; then
    export fpath=("$(brew --prefix)/share/zsh/site-functions" $fpath)
fi

for FILE in $(fd --glob '*.zsh' $ZDOTDIR); do
  source $FILE
done
